; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.arduino.partitions = app3M_fat9M_16MB.csv 
    
; Flash and PSRAM IO mode
board_build.arduino.memory_type = qio_opi ; or opi_opi, depending on your module
    
;Assert PSRAM presence
board_build.arduino.psram = enabled    
; Assert flash size
board_upload.flash_size = 16MB

monitor_filters =
    esp32_exception_decoder
build_type = debug